# Generated by Django 5.0.2 on 2024-05-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
